### ISSUE TITLE
[NEW-FEATURE] Meeting 16.03.2021

### ISSUE THREAD

**Issue by AndreaGrandieri** [AndreaGrandieri/MagicMirror-GBM#141]
## Brief

**TODO**
- [x] Cambi Template Documentazione Modulo
- [x] Riflessioni e considerazioni per Interfaccia IP
- [x] Proposte per testing moduli
